import styled from 'styled-components';
import { fadeIn, fadeOut } from './animations';
export const Container = styled.div`
  position: absolute;
  visibility: ${props => (props.status ? 'visible' : 'hidden')};
  animation: ${fadeOut} 1s linear;
  transition: visibility 1s linear;
  top: 50%;
  left: 50%;
  transform: translateY(-50%);
  transform: translateX(-50%);
  font-family: helvetica;
  font-size: 3.5rem;
  font-weight: bold;
  text-background: transparent;
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-image: linear-gradient(45deg, #fbda61 0%, #ff5acd 100%);
  z-index: 6;
`;
